[package]
name = "remote-email-filtering"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
email-lib = "0.19.6"
maybe-owned = "0.3.4"
rand = "0.8.5"
thiserror = "1.0.61"

[lib]
name = "remote_email_filtering"
path = "src/lib.rs"

[[bin]]
name = "filter-emails"
path = "src/main.rs"
